; Auto-generated. Do not edit!


(cl:in-package turtlebot_actions-msg)


;//! \htmlinclude ActionMsgMapperResult.msg.html

(cl:defclass <ActionMsgMapperResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ActionMsgMapperResult (<ActionMsgMapperResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionMsgMapperResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionMsgMapperResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot_actions-msg:<ActionMsgMapperResult> is deprecated: use turtlebot_actions-msg:ActionMsgMapperResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionMsgMapperResult>) ostream)
  "Serializes a message object of type '<ActionMsgMapperResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionMsgMapperResult>) istream)
  "Deserializes a message object of type '<ActionMsgMapperResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionMsgMapperResult>)))
  "Returns string type for a message object of type '<ActionMsgMapperResult>"
  "turtlebot_actions/ActionMsgMapperResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionMsgMapperResult)))
  "Returns string type for a message object of type 'ActionMsgMapperResult"
  "turtlebot_actions/ActionMsgMapperResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionMsgMapperResult>)))
  "Returns md5sum for a message object of type '<ActionMsgMapperResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionMsgMapperResult)))
  "Returns md5sum for a message object of type 'ActionMsgMapperResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionMsgMapperResult>)))
  "Returns full string definition for message of type '<ActionMsgMapperResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionMsgMapperResult)))
  "Returns full string definition for message of type 'ActionMsgMapperResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionMsgMapperResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionMsgMapperResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionMsgMapperResult
))
