; Auto-generated. Do not edit!


(cl:in-package turtlebot_actions-msg)


;//! \htmlinclude ActionMsgMapperFeedback.msg.html

(cl:defclass <ActionMsgMapperFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ActionMsgMapperFeedback (<ActionMsgMapperFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionMsgMapperFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionMsgMapperFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot_actions-msg:<ActionMsgMapperFeedback> is deprecated: use turtlebot_actions-msg:ActionMsgMapperFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionMsgMapperFeedback>) ostream)
  "Serializes a message object of type '<ActionMsgMapperFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionMsgMapperFeedback>) istream)
  "Deserializes a message object of type '<ActionMsgMapperFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionMsgMapperFeedback>)))
  "Returns string type for a message object of type '<ActionMsgMapperFeedback>"
  "turtlebot_actions/ActionMsgMapperFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionMsgMapperFeedback)))
  "Returns string type for a message object of type 'ActionMsgMapperFeedback"
  "turtlebot_actions/ActionMsgMapperFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionMsgMapperFeedback>)))
  "Returns md5sum for a message object of type '<ActionMsgMapperFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionMsgMapperFeedback)))
  "Returns md5sum for a message object of type 'ActionMsgMapperFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionMsgMapperFeedback>)))
  "Returns full string definition for message of type '<ActionMsgMapperFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionMsgMapperFeedback)))
  "Returns full string definition for message of type 'ActionMsgMapperFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionMsgMapperFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionMsgMapperFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionMsgMapperFeedback
))
